# Description des données

Le fichier thelook_fr_women_2023_2024.csv contient des données relatives aux ventes de vêtements pour femmes en France sur les années 2023 et 2024. Il est composé de 1 679 lignes et 20 colonnes, qui décrivent les commandes, les articles vendus, les prix, les coûts, les marques, les catégories de produits ainsi que les informations géographiques des clients.

Chaque ligne correspond à un article associé à une commande. Les principales variables disponibles comprennent la date de création de l’article, son prix de vente, son coût, sa marque, sa catégorie et la ville associée à la commande. Le fichier contient également des informations sur le statut des commandes, leur expédition et leur livraison.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/thelook_fr_women_2023_2024.csv")
print(f"Dimensions : {df.shape[0]:,} lignes × {df.shape[1]} colonnes")

df.info()
df.head()

Dimensions : 1,679 lignes × 20 colonnes
<class 'pandas.DataFrame'>
RangeIndex: 1679 entries, 0 to 1678
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1679 non-null   int64
 1   order_item_id     1679 non-null   int64
 2   product_id        1679 non-null   int64
 3   item_created_at   1679 non-null   str
 4   item_status       1679 non-null   str
 5   sale_price        1679 non-null   float64
 6   cost              1679 non-null   float64
 7   category          1679 non-null   str
 8   department        1679 non-null   str
 9   brand             1677 non-null   str
 10  product_name      1679 non-null   str
 11  order_status      1679 non-null   str
 12  order_created_at  1679 non-null   str
 13  shipped_at        1133 non-null   str
 14  delivered_at      636 non-null    str
 15  user_id           1679 non-null   int64
 16  gender            1679 non-null   str
 17  country           1679 non-null   str
 18  state             1679 non-null   str
 19  city              1679 non-null   str
dtypes: float64(2), int64(4), str(14)
memory usage: 262.5 KB

,order_id,order_item_id,product_id,item_created_at,item_status,sale_price,cost,category,department,brand,product_name,order_status,order_created_at,shipped_at,delivered_at,user_id,gender,country,state,city
0,19425,28112,6983,2023-01-01 06:18:03+00:00,Shipped,29.500000,16.048000,Shorts,Women,Fox,Fox Juniors Momentum Short,Shipped,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaN,15644,F,France,Centre-Val de Loire,Corquilleroy
1,19425,28113,10597,2023-01-01 06:44:58+00:00,Shipped,20.000000,10.000000,Intimates,Women,Wacoal,Wacoal Women's B-Smooth Bralette,Shipped,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaN,15644,F,France,Centre-Val de Loire,Corquilleroy
2,4710,6730,11792,2023-01-03 04:44:50+00:00,Complete,38.000000,18.468000,Intimates,Women,American Apparel,American Apparel Striped Chiffon Tank,Complete,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00,3853,F,France,Île-de-France,Paris
3,16618,24006,329,2023-01-03 15:13:39+00:00,Complete,27.990000,16.402140,Tops & Tees,Women,Tri-Mountain,Tri-Mountain Women's 3/4-Sleeve Pique Knit Pol...,Complete,2023-01-03 18:58:00+00:00,2023-01-05 13:23:00+00:00,2023-01-09 10:25:00+00:00,13422,F,France,Hauts-de-France,Comines
4,4710,6731,5295,2023-01-05 06:43:09+00:00,Complete,56.880001,29.577601,Pants & Capris,Women,Lauren by Ralph Lauren,Lauren Ralph Lauren Velour Pants,Complete,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00,3853,F,France,Île-de-France,Paris

In [7]:
#création du dictionnaire des données#
data_dict = {
    "order_id": ("Identifiant de la commande", "int64"),
    "order_item_id": ("Identifiant de l'article commandé", "int64"),
    "product_id": ("Identifiant du produit", "int64"),
    "item_created_at": ("Date de création de l'article", "str"),
    "item_status": ("Statut de l'article", "str"),
    "sale_price": ("Prix de vente de l'article", "float64"),
    "cost": ("Coût de l'article", "float64"),
    "category": ("Catégorie du produit", "str"),
    "department": ("Département du produit", "str"),
    "brand": ("Marque du produit", "str"),
    "product_name": ("Nom du produit", "str"),
    "order_status": ("Statut de la commande", "str"),
    "order_created_at": ("Date de création de la commande", "str"),
    "shipped_at": ("Date d'expédition de la commande", "str"),
    "delivered_at": ("Date de livraison de la commande", "str"),
    "user_id": ("Identifiant de l'utilisateur", "int64"),
    "gender": ("Genre de l'utilisateur", "str"),
    "country": ("Pays de l'utilisateur", "str"),
    "state": ("État de l'utilisateur", "str"),
    "city": ("Ville de l'utilisateur", "str"),
}

dictionnaire = pd.DataFrame.from_dict(data_dict, orient="index", columns=["Description", "Type de données"]).reset_index(names="Nom de la colonne")
dictionnaire

   Nom de la colonne                        Description Type de données
0           order_id         Identifiant de la commande           int64
1      order_item_id  Identifiant de l'article commandé           int64
2         product_id             Identifiant du produit           int64
3    item_created_at      Date de création de l'article             str
4        item_status                Statut de l'article             str
5         sale_price         Prix de vente de l'article         float64
6               cost                  Coût de l'article         float64
7           category               Catégorie du produit             str
8         department             Département du produit             str
9              brand                  Marque du produit             str
10      product_name                     Nom du produit             str
11      order_status              Statut de la commande             str
12  order_created_at    Date de création de la commande             str
13        shipped_at   Date d'expédition de la commande             str
14      delivered_at   Date de livraison de la commande             str
15           user_id       Identifiant de l'utilisateur           int64
16            gender             Genre de l'utilisateur             str
17           country              Pays de l'utilisateur             str
18             state              État de l'utilisateur             str
19              city             Ville de l'utilisateur             str